import pandas as pd
import duckdb

df = pd.read_csv('data/arg_def_m_20_22.csv')
df.info()
df.drop('grupo_causa_defuncion_CIE10', axis=1, inplace=True)
df.drop('mes_anio_defuncion', axis=1, inplace=True)
df.drop('sexo_id', axis=1, inplace=True)
df.head()
dfcie10 = pd.read_csv('data/Cie10.csv')
dfcie10.info()
dfcie10.head()
dfcie10grupo = pd.read_csv('data/Cie10Grupos.csv')
dfcie10grupo.info()
dfcie10grupo.head()
con = duckdb.connect('def20152021.duckdb')
con.execute("CREATE OR REPLACE TABLE defunciones AS SELECT * FROM df")
con.execute("CREATE OR REPLACE TABLE cie10 AS SELECT * FROM dfcie10")
con.execute("CREATE OR REPLACE TABLE cie10grupo AS SELECT * FROM dfcie10grupo")
print("\n--- Tablas creadas en DuckDB ---")
print(con.execute("SHOW TABLES").fetchdf())
print("--- Tabla defunciones ---")
print(con.execute("DESCRIBE defunciones").fetchdf())
print(con.execute("select * from defunciones limit 5").fetchdf())
print("--- Tabla cie10 ---")
print(con.execute("DESCRIBE cie10").fetchdf())
print(con.execute("select * from cie10 limit 5").fetchdf())
print("--- Tabla cie10grupo ---")
print(con.execute("DESCRIBE cie10grupo").fetchdf())
print(con.execute("select id,descripcion from cie10grupo limit 5").fetchdf())
con.close()